import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Menu from "@/components/menu/menu";
import MainSlider from "@/components/mainSlider/mainSlider";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "swiper/css/free-mode";
import "swiper/css/thumbs";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <Theme>
          <Navbar />
          <Menu />
          {children}
        </Theme>
      </body>
    </html>
  );
}
