
import type { Metadata } from 'next'

import './globals.css'
import Navbar from '@/components/navbar/navbar'
import Menu from '@/components/menu/menu'
import MainSlider from '@/components/mainSlider/mainSlider'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body >
      <Navbar />
      <Menu/>
      {/* <MainSlider/> */}
      {children}
      </body>
    </html>
  )
}
